apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jk4m6bzlf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jk4m6bzlf-go 
  name: jk4m6bzlf-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jk4m6bzlf-go
    weight: 100 
