apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jk4m6bzlf-go 
  janus-idp.io/tekton: jk4m6bzlf-go
  backstage.io/kubernetes-id: jk4m6bzlf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jk4m6bzlf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml